
#-----   ddr3 -----#
set_property -dict "PACKAGE_PIN AF17 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[0]}]; # IO_L1N_T0_32 
set_property -dict "PACKAGE_PIN AE17 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[1]}]; # IO_L1P_T0_32 
set_property -dict "PACKAGE_PIN AF15 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[2]}]; # IO_L2N_T0_32 
set_property -dict "PACKAGE_PIN AF14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[3]}]; # IO_L2P_T0_32 
set_property -dict "PACKAGE_PIN AE15 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[4]}]; # IO_L4N_T0_32 
set_property -dict "PACKAGE_PIN AD15 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[5]}]; # IO_L4P_T0_32 
set_property -dict "PACKAGE_PIN AF20 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[6]}]; # IO_L5N_T0_32 
set_property -dict "PACKAGE_PIN AF19 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[7]}]; # IO_L5P_T0_32 
set_property -dict "PACKAGE_PIN AA15 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[8]}]; # IO_L7N_T1_32 
set_property -dict "PACKAGE_PIN AA14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[9]}]; # IO_L7P_T1_32 
set_property -dict "PACKAGE_PIN AC14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[10]}]; # IO_L8P_T1_32 
set_property -dict "PACKAGE_PIN AD14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[11]}]; # IO_L8N_T1_32 
set_property -dict "PACKAGE_PIN AB14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[12]}]; # IO_L10P_T1_32 
set_property -dict "PACKAGE_PIN AB15 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[13]}]; # IO_L10N_T1_32 
set_property -dict "PACKAGE_PIN AA18 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[14]}]; # IO_L11N_T1_SRCC_32 
set_property -dict "PACKAGE_PIN AA17 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[15]}]; # IO_L11P_T1_SRCC_32 
set_property -dict "PACKAGE_PIN AC18 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[16]}]; # IO_L13P_T2_MRCC_32 
set_property -dict "PACKAGE_PIN AD18 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[17]}]; # IO_L13N_T2_MRCC_32 
set_property -dict "PACKAGE_PIN AC17 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[18]}]; # IO_L14N_T2_SRCC_32 
set_property -dict "PACKAGE_PIN AB17 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[19]}]; # IO_L14P_T2_SRCC_32 
set_property -dict "PACKAGE_PIN AA20 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[20]}]; # IO_L16N_T2_32 
set_property -dict "PACKAGE_PIN AA19 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[21]}]; # IO_L16P_T2_32 
set_property -dict "PACKAGE_PIN AD19 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[22]}]; # IO_L17N_T2_32 
set_property -dict "PACKAGE_PIN AC19 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[23]}]; # IO_L17P_T2_32 
set_property -dict "PACKAGE_PIN W14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[24]}]; # IO_L24N_T3_32 
set_property -dict "PACKAGE_PIN V14 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[25]}]; # IO_L24P_T3_32 
set_property -dict "PACKAGE_PIN V19 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[26]}]; # IO_L23N_T3_32 
set_property -dict "PACKAGE_PIN V18 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[27]}]; # IO_L23P_T3_32 
set_property -dict "PACKAGE_PIN V16 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[28]}]; # IO_L20P_T3_32 
set_property -dict "PACKAGE_PIN W15 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[29]}]; # IO_L22P_T3_32 
set_property -dict "PACKAGE_PIN W16 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[30]}]; # IO_L22N_T3_32 
set_property -dict "PACKAGE_PIN Y17 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[31]}]; # IO_L19P_T3_32 
set_property -dict "PACKAGE_PIN V4 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[32]}]; # IO_L6P_T0_34 
set_property -dict "PACKAGE_PIN U6 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[33]}]; # IO_L1P_T0_34 
set_property -dict "PACKAGE_PIN U5 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[34]}]; # IO_L1N_T0_34 
set_property -dict "PACKAGE_PIN U2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[35]}]; # IO_L2P_T0_34 
set_property -dict "PACKAGE_PIN V3 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[36]}]; # IO_L4P_T0_34 
set_property -dict "PACKAGE_PIN W3 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[37]}]; # IO_L4N_T0_34 
set_property -dict "PACKAGE_PIN U7 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[38]}]; # IO_L5P_T0_34 
set_property -dict "PACKAGE_PIN V6 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[39]}]; # IO_L5N_T0_34 
set_property -dict "PACKAGE_PIN Y3 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[40]}]; # IO_L7P_T1_34 
set_property -dict "PACKAGE_PIN Y2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[41]}]; # IO_L7N_T1_34 
set_property -dict "PACKAGE_PIN V2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[42]}]; # IO_L8P_T1_34 
set_property -dict "PACKAGE_PIN V1 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[43]}]; # IO_L8N_T1_34 
set_property -dict "PACKAGE_PIN W1 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[44]}]; # IO_L10P_T1_34 
set_property -dict "PACKAGE_PIN Y1 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[45]}]; # IO_L10N_T1_34 
set_property -dict "PACKAGE_PIN AB2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[46]}]; # IO_L11P_T1_SRCC_34 
set_property -dict "PACKAGE_PIN AC2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[47]}]; # IO_L11N_T1_SRCC_34 
set_property -dict "PACKAGE_PIN AA4 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[48]}]; # IO_L13P_T2_MRCC_34 
set_property -dict "PACKAGE_PIN AB4 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[49]}]; # IO_L13N_T2_MRCC_34 
set_property -dict "PACKAGE_PIN AC4 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[50]}]; # IO_L14P_T2_SRCC_34 
set_property -dict "PACKAGE_PIN AC3 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[51]}]; # IO_L14N_T2_SRCC_34 
set_property -dict "PACKAGE_PIN AC6 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[52]}]; # IO_L16N_T2_34 
set_property -dict "PACKAGE_PIN AB6 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[53]}]; # IO_L16P_T2_34 
set_property -dict "PACKAGE_PIN Y6 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[54]}]; # IO_L17P_T2_34 
set_property -dict "PACKAGE_PIN Y5 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[55]}]; # IO_L17N_T2_34 
set_property -dict "PACKAGE_PIN AD4 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[56]}]; # IO_L19P_T3_34 
set_property -dict "PACKAGE_PIN AD1 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[57]}]; # IO_L20P_T3_34 
set_property -dict "PACKAGE_PIN AF2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[58]}]; # IO_L24N_T3_34 
set_property -dict "PACKAGE_PIN AE2 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[59]}]; # IO_L22N_T3_34 
set_property -dict "PACKAGE_PIN AE6 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[60]}]; # IO_L23P_T3_34 
set_property -dict "PACKAGE_PIN AE5 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[61]}]; # IO_L23N_T3_34 
set_property -dict "PACKAGE_PIN AF3 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[62]}]; # IO_L24P_T3_34 
set_property -dict "PACKAGE_PIN AE3 IOSTANDARD SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dq[63]}]; # IO_L22P_T3_34 
set_property -dict "PACKAGE_PIN AB12 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[14]}];
set_property -dict "PACKAGE_PIN AF7 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[13]}]; # IO_L7N_T1_33 
set_property -dict "PACKAGE_PIN AE13 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[12]}]; # IO_L23P_T3_33 
set_property -dict "PACKAGE_PIN AD10 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[11]}]; # IO_L20P_T3_33 
set_property -dict "PACKAGE_PIN AF9 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[10]}]; # IO_L24N_T3_33 
set_property -dict "PACKAGE_PIN AF12 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[9]}]; # IO_L21N_T3_DQS_33 
set_property -dict "PACKAGE_PIN AC13 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[8]}]; # IO_L17P_T2_33 
set_property -dict "PACKAGE_PIN AD8 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[7]}]; # IO_L9N_T1_DQS_33 
set_property -dict "PACKAGE_PIN AC8 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[6]}]; # IO_L9P_T1_DQS_33 
set_property -dict "PACKAGE_PIN AE11 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[5]}]; # IO_L19N_T3_VREF_33 
set_property -dict "PACKAGE_PIN AC7 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[4]}]; # IO_L10N_T1_33 
set_property -dict "PACKAGE_PIN AF10 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[3]}]; # IO_L24P_T3_33 
set_property -dict "PACKAGE_PIN AA8 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[2]}]; # IO_L8P_T1_33 
set_property -dict "PACKAGE_PIN AD11 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[1]}]; # IO_L19P_T3_33 
set_property -dict "PACKAGE_PIN AB7 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_addr[0]}]; # IO_L10P_T1_33 

set_property -dict "PACKAGE_PIN AF13 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_ba[2]}]; # IO_L23N_T3_33 
set_property -dict "PACKAGE_PIN AA7 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_ba[1]}]; # IO_L8N_T1_33 
set_property -dict "PACKAGE_PIN AE8 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_ba[0]}]; # IO_L22P_T3_33 
set_property -dict "PACKAGE_PIN Y7 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_ras_n } ]; # IO_L4N_T0_33 
set_property -dict "PACKAGE_PIN AE7 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_cas_n } ]; # IO_L7P_T1_33 
set_property -dict "PACKAGE_PIN AF8 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_we_n } ]; # IO_L22N_T3_33 
set_property -dict "PACKAGE_PIN AB20 IOSTANDARD LVCMOS15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_reset_n } ]; # IO_L18N_T2_32 

set_property -dict "PACKAGE_PIN AA9 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_cke[1]}]; # 
set_property -dict "PACKAGE_PIN Y13 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_odt[1]}]; # 
set_property -dict "PACKAGE_PIN AD13 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_cs_n[1]}]; # 
set_property -dict "PACKAGE_PIN AB9 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_cke[0]}]; # IO_L11N_T1_SRCC_33 
set_property -dict "PACKAGE_PIN AA12 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_odt[0]}]; # IO_L16N_T2_33 
set_property -dict "PACKAGE_PIN AA13 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_cs_n[0]}]; # IO_L16P_T2_33 

set_property -dict "PACKAGE_PIN AD16 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[0]}]; # IO_L6P_T0_32 
set_property -dict "PACKAGE_PIN AB16 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[1]}]; # IO_L12P_T1_MRCC_32 
set_property -dict "PACKAGE_PIN AB19 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[2]}]; # IO_L18P_T2_32 
set_property -dict "PACKAGE_PIN V17 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[3]}]; # IO_L20N_T3_32 
set_property -dict "PACKAGE_PIN U1 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[4]}]; # IO_L2N_T0_34 
set_property -dict "PACKAGE_PIN AA3 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[5]}]; # IO_L12P_T1_MRCC_34 
set_property -dict "PACKAGE_PIN AD6 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[6]}]; # IO_L18P_T2_34 
set_property -dict "PACKAGE_PIN AE1 IOSTANDARD SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dm[7]}]; # IO_L20N_T3_34 
set_property -dict "PACKAGE_PIN AE18 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[0]}]; # IO_L3P_T0_DQS_32 
set_property -dict "PACKAGE_PIN AF18 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[0]}]; # IO_L3N_T0_DQS_32 
set_property -dict "PACKAGE_PIN Y15 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[1]}]; # IO_L9P_T1_DQS_32 
set_property -dict "PACKAGE_PIN Y16 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[1]}]; # IO_L9N_T1_DQS_32 
set_property -dict "PACKAGE_PIN AD20 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[2]}]; # IO_L15P_T2_DQS_32 
set_property -dict "PACKAGE_PIN AE20 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[2]}]; # IO_L15N_T2_DQS_32 
set_property -dict "PACKAGE_PIN W18 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[3]}]; # IO_L21P_T3_DQS_32 
set_property -dict "PACKAGE_PIN W19 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[3]}]; # IO_L21N_T3_DQS_32 
set_property -dict "PACKAGE_PIN W6 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[4]}]; # IO_L3P_T0_DQS_34 
set_property -dict "PACKAGE_PIN W5 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[4]}]; # IO_L3N_T0_DQS_34 
set_property -dict "PACKAGE_PIN AB1 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[5]}]; # IO_L9P_T1_DQS_34 
set_property -dict "PACKAGE_PIN AC1 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[5]}]; # IO_L9N_T1_DQS_34 
set_property -dict "PACKAGE_PIN AA5 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[6]}]; # IO_L15P_T2_DQS_34 
set_property -dict "PACKAGE_PIN AB5 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[6]}]; # IO_L15N_T2_DQS_34 
set_property -dict "PACKAGE_PIN AF5 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_p[7]}]; # IO_L21P_T3_DQS_34 
set_property -dict "PACKAGE_PIN AF4 IOSTANDARD DIFF_SSTL15_T_DCI VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_dqs_n[7]}]; # IO_L21N_T3_DQS_34 
set_property -dict "PACKAGE_PIN AC9 IOSTANDARD DIFF_SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_ck_p[0]}]; # IO_L12P_T1_MRCC_33 
set_property -dict "PACKAGE_PIN AD9 IOSTANDARD DIFF_SSTL15 VCCAUX_IO NORMAL SLEW FAST" [get_ports {ddr3_ck_n[0]}]; # IO_L12N_T1_MRCC_33 

